###
POST http://127.0.0.1:8000/api/users
Content-Type: application/json
Accept: application/json

{
    "email":"admin@mail.com",
    "password":"password"
}
###

###
GET http://127.0.0.1:8000/api/users
Content-Type: application/json
Accept: application/json
Authorization: a476be2f-3cfd-428c-958f-55046c03770c


###

###
DELETE http://127.0.0.1:8000/api/users
Content-Type: application/json
Accept: application/json
Authorization: a476be2f-3cfd-428c-958f-55046c03770c
###
